language: node_js
node_js:
  - "7"

script:
    - npm start

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: "./build"
  provider: pages
  skip_cleanup: true
  target_branch: "gh-pages"
  on:
    branch: master
